# Setup
title:               Mingkun Lei
tagline:             'Personal Site'
description:         'A personal site'
url:                 https://mingkunlei.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mingkun Lei
  url:               https://github.com/MingkunLei
  email:             leimingkun@westlake.edu.cn

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
